# Generated by Django 4.1.7 on 2023-03-29 17:17

from django.db import migrations, models
import django.db.models.deletion
import movies_rest_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year', validators=[movies_rest_app.models.before_current_year])),
                ('nominations_type', models.CharField(db_column='nominations type', max_length=256)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_rest_app.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_rest_app.movie')),
            ],
            options={
                'db_table': 'oscar',
                'unique_together': {('year', 'nominations_type')},
            },
        ),
    ]
